<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a very simple XSL stylesheet for taking data from a top artists chart and rendering it as plain text, one artist per line -->
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<xsl:output method="text"/>

	<xsl:template match="/">
		<xsl:text>/* Autogenerated */&#xa;&#xa;</xsl:text>
		<xsl:for-each select="//artist">
			<xsl:value-of select="@rank" />
			<xsl:text>&#x09;</xsl:text>
			<xsl:value-of select="name" />
			<xsl:text>&#x09;</xsl:text>
			<xsl:value-of select="playcount" />
			<xsl:text>&#x09;</xsl:text>
			<xsl:text>&#xa;</xsl:text>
		</xsl:for-each>

		<xsl:for-each select="//platform">
														
			<xsl:for-each select="interfaceList/interface[@bypass='yes']">
			</xsl:for-each>
		</xsl:for-each>
	</xsl:template>
</xsl:stylesheet>
